data sources:
  # The data sources will be loaded in the order they are populated here
  - name: MIDRC
    description: MIDRC TSV File
    data type: file
    filename: data/midrc_data_download-2025-01-29.tsv
    columns:
      - Age at Index
      - Ethnicity
      - Race
      - Sex
      - COVID-19 Positive
      - Race and Ethnicity
    numeric_cols:
      Age at Index:
        raw column: age_at_index
        bins: [ 0, 5, 12, 16, 18, 30, 40, 50, 65, 75, 85, 1000 ]
        labels: [ '0-4', '5-11', '12-15', '16-17', '18-29', '30-39', '40-49', '50-64', '65-74', '75-84', '85+' ]
    plugin: midrc_tsv_loader

  - name: CDC
    description: CDC Excel File
    data type: file
    filename: data/CDC_COVIDpos - cumulative by month.xlsx

  - name: Census
    description: Census Excel File
    data type: file
    filename: data/Census_all.xlsx
    date: '2020-01-01' # The census file does not have a date column, so we specify the date here

  - name: MIDRC COVID+
    description: MIDRC COVID+ TSV File
    data type: file
    filename: data/midrc_data_download-2025-01-29_covid_pos.tsv
    columns:
      - Age at Index
      - Ethnicity
      - Race
      - Sex
      - COVID-19 Positive
      - Race and Ethnicity
    numeric_cols:
      Age at Index:
        raw column: age_at_index
        bins: [ 0, 5, 12, 16, 18, 30, 40, 50, 65, 75, 85, 1000 ]
        labels: [ '0-4', '5-11', '12-15', '16-17', '18-29', '30-39', '40-49', '50-64', '65-74', '75-84', '85+' ]
    plugin: midrc_tsv_loader

  - name: Zip Code 1
    description: Zip Code 1 TSV File
    data type: file
    filename: data/midrc_data_download-2025-01-29_0.tsv
    columns:
      - Age at Index
      - Ethnicity
      - Race
      - Sex
      - COVID-19 Positive
      - Race and Ethnicity
    numeric_cols:
      Age at Index:
        raw column: age_at_index
        bins: [ 0, 5, 12, 16, 18, 30, 40, 50, 65, 75, 85, 1000 ]
        labels: [ '0-4', '5-11', '12-15', '16-17', '18-29', '30-39', '40-49', '50-64', '65-74', '75-84', '85+' ]
    plugin: midrc_tsv_loader

  - name: Zip Code 2
    description: Zip Code 2 TSV File
    data type: file
    filename: data/midrc_data_download-2025-01-29_1.tsv
    columns:
      - Age at Index
      - Ethnicity
      - Race
      - Sex
      - COVID-19 Positive
      - Race and Ethnicity
    numeric_cols:
      Age at Index:
        raw column: age_at_index
        bins: [ 0, 5, 12, 16, 18, 30, 40, 50, 65, 75, 85, 1000 ]
        labels: [ '0-4', '5-11', '12-15', '16-17', '18-29', '30-39', '40-49', '50-64', '65-74', '75-84', '85+' ]
    plugin: midrc_tsv_loader

  - name: MIDRC COVID+
    description: MIDRC COVID+ Excel File
    data type: file
    filename: data/MIDRC Open A1 and R1 COVIDpos only - cumulative by batch.xlsx
    remove column name text: [(CUSUM)]

  - name: MIDRC
    description: MIDRC Excel File
    data type: file
    filename: data/MIDRC Open A1 and R1 - cumulative by batch.xlsx
    remove column name text: [(CUSUM)]

# TODO: The following should be moved into QSettings for modifications within the GUI
# For custom age columns, please use .inf as the maximum age in the final age group
custom age ranges:
  Age at Index: [ [0, 17], [18, 49], [50, 64], [65, .inf] ]
